[package]
name = "pix"
version = "0.1.0"
authors = ["Douglas Lau <doug.p.lau@gmail.com>"]
description = "Pixel / raster image library"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/pix"
homepage = "https://github.com/DougLau/pix"
repository = "https://github.com/DougLau/pix"
readme = "README.md"
keywords = ["image", "pixel", "compositing", "blend"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "over"
harness = false

[features]
default = ["use-simd"]
use-simd = []
